### ISSUE TITLE
onAsObservable causing runtime error

### ISSUE THREAD

**Issue by yemi** [anttih/purescript-rx#9]
Getting `Uncaught TypeError: ob.onAsObservable is not a function` when doing:
``` purescript
main = do 
  testDiv <- J.select ".test"
  clicks <- onAsObservable "click" testDiv
```

**Comment by anttih** [comment]
The jQuery functions require that you have the (RxJS-jQuery)[https://github.com/Reactive-Extensions/RxJS-jQuery] extension on the page. Can you try adding that to the page and see if you can get it working?

I'll need to update the docs to make this clear, so thanks for reporting!

**Comment by yemi** [comment]
Right that works ofc, should've noticed earlier! But how come the standard `fromEvent` function isn't ported? Whats the benefit of using the extra RxJs-jQuery library here?

**Comment by anttih** [comment]
That's a good question, I can't remember why. What we really want is the `onAsObservable` which calls jQuery's `on` so that it does event delegation (the old "live"). I'm in the process of extracting the jQuery stuff into a separate library.
